# Generated by Django 4.2.8 on 2023-12-17 08:09

import app1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', models.SlugField(unique_for_date='publish')),
                ('short_des', models.CharField(max_length=30, verbose_name='Description')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create_date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update_date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255, verbose_name='status')),
                ('img', models.ImageField(blank=True, upload_to='pictures/', verbose_name='picture')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='PostPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_point_text', models.TextField(verbose_name='Post_point')),
                ('post_img', models.ImageField(blank=True, upload_to=app1.models.save_img, verbose_name='picture_point')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.post')),
            ],
        ),
    ]
