# Generated by Django 5.0 on 2024-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_img_alter_post_short_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create_date'),
        ),
    ]
