# Generated by Django 4.2.9 on 2024-01-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_postpoint_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Title')),
                ('emeil', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Create_date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update_date')),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app1.post')),
            ],
            options={
                'ordering': ['-date_create'],
                'indexes': [models.Index(fields=['-date_create'], name='app1_commen_date_cr_90e87b_idx')],
            },
        ),
    ]
