# Generated by Django 4.2.11 on 2024-04-28 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0009_alter_post_managers_alter_postpoint_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_p', to=settings.AUTH_USER_MODEL),
        ),
    ]
