# Generated by Django 4.2.11 on 2024-06-02 06:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_postpoint_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoint',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postpoint',
            name='video',
            field=models.FileField(blank=True, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
